- platform: template
  sensors:
    hall_door_sensor_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.enter_opening_sensor_burglar', '3') }}"
    living_room_window_opening_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.living_room_opening_sensor_burglar', '3') }}"
    dining_room_window_opening_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.dining_room_opening_sensor_burglar', '3') }}"
    cellar_motion_sensor_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.cellar_motion_sensor_burglar', '3') }}"
    bar_window_opening_sensor_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.bar_opening_sensor_burglar', '3') }}"
    kitchen_window_opening_sensor_burglar:
      friendly_name: "Arrachement"
      device_class: safety
      value_template: "{{ is_state('sensor.kitchen_opening_sensor_burglar', '3') }}"

