version: '2'

services:  
  hass:
    image: homeassistant/home-assistant
    hostname: hass
    container_name: hass
    restart: always
    
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0

    network_mode: "host"

