- platform: yr

- platform: bbox
  name: Bbox
  monitored_variables:
    - down_max_bandwidth
    - up_max_bandwidth
    - current_down_bandwidth
    - current_up_bandwidth
    - uptime
    - number_of_reboots

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_15m
    - type: process
      arg: octave-cli
    - type: processor_use
    - type: last_boot
    - type: ipv4_address
      arg: enp2s0
    - type: packets_in
      arg: enp2s0
    - type: packets_out
      arg: enp2s0
    - type: throughput_network_in
      arg: enp2s0
    - type: throughput_network_out
      arg: enp2s0
    - type: network_in
      arg: enp2s0
    - type: network_out
      arg: enp2s0
    - type: swap_use_percent
