zwave.living_room:
  polling_intensity: 1
zwave.bedroom:
  polling_intensity: 1
light.living_room:
  ignored: false
  polling_intensity: 1
sensor.living_room_power:
  ignored: false
  polling_intensity: 1
light.bedroom:
  ignored: false
  polling_intensity: 1
zwave.cellar:
  ignored: false
  polling_intensity: 1
binary_sensor.enter_door_sensor:
  ignored: false
  polling_intensity: 30
