- alias: Trigger alarm while armed away
  trigger:
    - platform: state
      entity_id: group.opening_window_doors_sensors
      to: 'on'
    - platform: state
      entity_id: group.opening_window_doors_burglar
      to: 'on'
    - platform: state
      entity_id: input_boolean.inside_camera_detection
  condition:
    - condition: state
      entity_id: alarm_control_panel.house_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house_alarm

- alias: Send notification when alarm triggered
  trigger:
    platform: state
    entity_id: alarm_control_panel.house_alarm
    to: 'triggered'
  action:
    - service: notify.system_group
      data:
        message: "ALARM! The alarm has been triggered"
    - service: light.turn_on
      data:
        brightness: 250
        entity_id: group.lights 

    - service: cover.open_cover
      entity_id: group.covers
      
- alias: Switch off Synology Surveillance Station HomeMode
  trigger:
    platform: state
    entity_id: alarm_control_panel.house_alarm
    to: 'armed_away'
  action:
    - service: rest_command.turn_off_synology_home_mode
      
- alias: Switch on Synology Surveillance Station HomeMode
  trigger:
    platform: state
    entity_id: alarm_control_panel.house_alarm
    to: 'disarmed'
  action:
    - service: rest_command.turn_on_synology_home_mode