- alias: 'Trigger alarm while armed away'
  trigger:
    #- platform: state
    #  entity_id: sensor.pir1
    #  to: 'active'
    #- platform: state
    #  entity_id: sensor.pir2
    #  to: 'active'
    #- platform: state
    #  entity_id: sensor.door
    #  to: 'open'
    #- platform: state
    #  entity_id: sensor.window
    #  to: 'open'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    - service: notify.system_group
      data:
        message: "ALARM! The alarm has been triggered"
