- alias: Déclanche l'alarme par les capteurs
  trigger:
    - platform: state
      entity_id: group.opening_window_doors_sensors
      to: 'on'
    - platform: state
      entity_id: group.opening_window_doors_burglar
      to: 'on'
    - platform: state
      entity_id: input_boolean.inside_camera_detection
  condition:
    - condition: state
      entity_id: alarm_control_panel.house_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house_alarm
    
- alias: Déclanche l'alarme par le détection de mouvement de la caméra de la salle à manger
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_camera_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house_alarm
      state: armed_away
    - condition: state
      entity_id: input_boolean.enable_dining_room_camera_motion_for_alarm
      state: 'on'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house_alarm

- alias: Envoi une notification quand l'alarme de déclanche
  trigger:
    platform: state
    entity_id: alarm_control_panel.house_alarm
    to: 'triggered'
  action:
    - service: notify.system_group
      data:
        message: "ALARM! The alarm has been triggered"
    - service: light.turn_on
      data:
        brightness: 250
        entity_id: group.lights 

    - service: cover.open_cover
      entity_id: group.covers