- alias: Ouverture auto du store du salon
  trigger:
    platform: sun
    event: sunrise
  action:
    service: cover.open_cover
    entity_id: cover.living_room
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_window_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.auto_open_covers
      state: 'on'

- alias: Ouverture auto du store de la salle à manger
  trigger:
    platform: sun
    event: sunrise
  action:
    service: cover.open_cover
    entity_id: cover.dining_room
  condition:
    - condition: state
      entity_id: binary_sensor.dining_room_window_opening_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.auto_open_covers
      state: 'on'

- alias: Ouverture auto du store du bar
  trigger:
    platform: sun
    event: sunrise
  action:
    service: cover.open_cover
    entity_id: cover.bar
  condition:
    - condition: state
      entity_id: binary_sensor.bar_window_opening_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.auto_open_covers
      state: 'on'

- alias: Ouverture auto du store du bar
  trigger:
    platform: sun
    event: sunrise
  action:
    service: cover.open_cover
    entity_id: cover.kitchen
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_window_opening_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.auto_open_covers
      state: 'on'

- alias: Fermeture auto des volets
  trigger:
    platform: sun
    event: sunset
  action:
    service: cover.close_cover
    entity_id: group.covers
  condition:
    - condition: state
      entity_id: input_boolean.auto_close_covers
      state:  'on'
