- alias: Fermeture auto des volets
  trigger:
    platform: sun
    event: sunset
  action:
    service: cover.close_cover
    entity_id: group.covers

- alias: Ouverture auto des volets
  trigger:
    platform: sun
    event: sunrise
  action:
    service: cover.open_cover
    entity_id: group.downstair_covers 
