- alias: allumage auto cellier
  trigger:
    platform: state
    entity_id: binary_sensor.cellar_motion_sensor_sensor
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.cellar

- alias: extinction auto cellier
  trigger:
    platform: state
    entity_id: binary_sensor.cellar_motion_sensor_sensor
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.cellar

