- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start
    - service: notify.system_group
      data:
        message: "Homekit demarre !"

- alias: 'camera motion sensor'
  trigger:
    - platform: webhook
      webhook_id: motion_sensor_inside
  action:
    - service: script.turn_on
      entity_id: script.trigger_inside_camera_detection


